name = 'My Game'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad',
    './title-screen'
]

[titleScreen]
  mongodb = 'mongodb://localhost:27017/test'

[start]
    map = 'simplemap'
    graphic = 'hero'
    hitbox = [16, 16]
